export const CALCULATE_REQUEST = 'CALCULATE_REQUEST';
export const CALCULATE_SUCCESS = 'CALCULATE_SUCCESS';
export const CALCULATE_FAILURE = 'CALCULATE_FAILURE';
export const MOVE_RESULT_TO_TOP = 'MOVE_RESULT_TO_TOP';
