export const CALCULATE_REQUEST = 'CALCULATE_REQUEST';
export const CALCULATE_SUCCESS = 'CALCULATE_SUCCESS';
export const CALCULATE_FAILURE = 'CALCULATE_FAILURE';
export const MOVE_RESULT_TO_TOP = 'MOVE_RESULT_TO_TOP';
export const CALCULATION_DELETE_REQUEST = 'CALCULATION_DELETE_REQUEST';
export const DELETE_RESULT_SUCCESS = 'DELETE_RESULT_SUCCESS';
export const RESULT_LOADED = 'RESULT_LOADED';
