export const WALLPAPER_LOAD_REQUEST = 'WALLPAPER_LOAD_REQUEST';
export const WALLPAPER_LOAD_STARTED = 'WALLPAPER_LOAD_STARTED';
export const WALLPAPER_LOAD_SUCCESS = 'WALLPAPER_LOAD_SUCCESS';
export const WALLPAPER_LOAD_FAILURE = 'WALLPAPER_LOAD_FAILURE';
